project_id = "yvqppebjznoaixyhxhot"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[auth.email]

[rest]
enabled = true
port = 54327

[realtime]
enabled = true
port = 54328

[functions.monitoring-webhook]
verify_jwt = false