// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvqppebjznoaixyhxhot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2cXBwZWJqem5vYWl4eWh4aG90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODAxNjksImV4cCI6MjA2OTU1NjE2OX0.vS_cLnWo5hu2IcYsHW5LGwUnGHWePaRJS3jScTWCiMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});